$$$b5.entrance
$$$b5.q1
$$$b5.q2
$$$b5.d1
$$$b5.d2
$$$b5.alien
$$$b5.garden
$$$b5.epsilon
$$$b5.down
$$$b5.cc
$$$b5.market
$$$b5.restaurant
$$$b5.end
$$$b5.tng
$$$b5.prs
$$dummy
$start_long
$start_short
$$system
$heavy/1
This can't work because it's too heavy for you.
$heavy/2
Be serious that's far too heavy.
$heavy/3
You may hurt - try something lighter.
$nomove
This can not be moved.
$nocomm/1
I do not understand. Perhaps you should try the help function.
$nocomm/2
Give me correct orders. Or try using help for some advice.
$nocomm/3
I can't do this. Try the help option for an example of useful commands.
$noway/1
I see no exit. You should take a better look.
$noway/2
Hey guy, use the normal paths as any other creature.
$noaction/1
This command is allowed but doesn't fit in the situation. Perhaps you
should try it somewhere else.
$noaction/2
I don't know how to do this at this place. Think of it once more.
$noaction/3
I don't understand you. Please slow down and explain.
$clock1
It's somewhat around
$clock2
o'clock.
$day0
Monday
$day1
Tuesday
$day2
Wednesday
$day3
Thursday
$day4
Friday
$day5
Saturday
$day6
Sunday
$stopit
