$$restaurant
$paterre_lang
Du bist im Eingangsbereich eines chinesischen Restaurants. Links ist eine
Preistafel angebracht. Die Preise scheinen Dir ebenfalls einigermaßen
angebracht. Eine steile Treppe führt nach oben, und hinter Dir ist der Ausgang.
$paterre_kurz
Du bist am unteren Ende der Treppe des Chinarestaurants.
$treppe_lang
Du steigst auf einer Art Wendeltreppe hoch. Die Treppe scheint kein Ende
zu nehmen. Allerlei bunter Schnickschnack an den Wänden und der Decke
verziert, oder sagen wir besser ergänzt, die Umgebung. Die Treppe setzt
sich nach oben und unten fort.
$treppe_kurz
Du bist auf der Wendeltreppe.
$theke_lang
Du hast einen großen Schankraum erreicht. Der mit vielen fernöstlichen
Kleinodien ausgestattete Raum vermittelt Dir einen sehr einladenden Eindruck.
Die meisten Tische sind leer, nur auf einem stehen ungefähr 20 leere
Pilsgläser der größeren Sorte.
$theke_kurz
Du bist im chinesischen Restaurant.
